name: CI for Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          sudo apt-get update  
          sudo apt-get install -y default-jdk  
          java -version  
          echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" >> $GITHUB_ENV  

      - name: Verify Java installation
        run: |
          echo $JAVA_HOME  
          java -version  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install nbconvert nbclient ipykernel

      - name: Setup Ollama
        run : |
          curl https://ollama.ai/install.sh | sh
          nohup ollama serve > ollama_serve.log 2>&1 &  
          sleep 10
          ollama pull granite-code:3b

      - name: Run Jupyter Notebooks
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          EXCLUDED_NOTEBOOKS: "recipes/Fine_Tuning_Granite/Finetuning_Granite.ipynb"
        run: |
          excluded_notebooks=$(echo $EXCLUDED_NOTEBOOKS | tr ',' '\n')

          for notebook in $(find . -name '*.ipynb'); do  
            skip=false
            for excluded in $excluded_notebooks; do
              if [[ "$notebook" == *"$excluded"* ]]; then
                echo "Skipping $notebook as it is in the excluded list"
                skip=true
                break
              fi
            done

            if [ "$skip" = false ]; then
              echo "Executing $notebook"
              jupyter nbconvert --to notebook --execute --inplace $notebook
            fi
          done
      
